import type { Metadata } from "next";
import "../styles/globals.css";
import React from "react";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="font-sans grid grid-rows-[20px_1fr_20px] items-center justify-items-center min-h-screen pt-8 pb-20 gap-16">
        <section className="flex gap-6">
          <Link href="/" id="paginaAtual">Lista Orçamentos</Link>
          <Link href="/contatos">Contatos</Link>
          <Link href="/">Usuários</Link>
          <Link href="/">Relatórios</Link>
          <Link href="/">Sair</Link>
        </section>
        {children}
        </div>
        </body>
    </html>
  );
}
